server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://rm-bp1h5384h1ot9ztbrfo.mysql.rds.aliyuncs.com:3306/cloud_order?useSSL=false
    username: root
    password: Hxx&Wyj_22-3-8@private
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderservice
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: zhangsan   #集群名称 自定义
        namespace: 6cb154cb-2207-4488-a63f-724a54729f33 #命名空间设置   id
        ephemeral: false  #是否是临时实列
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    fetch-registry: true
userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # 负载均衡规则

ribbon:
  eager-load:  #开启饥饿加载
    clients:
      -userservice